# Generated by Django 2.2.5 on 2019-10-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='destination'),
        ),
    ]
