# Generated by Django 2.2.5 on 2019-10-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191026_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='destination'),
        ),
    ]
