# Generated by Django 2.2.5 on 2019-11-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191026_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload_pics'),
        ),
    ]
