# Generated by Django 2.2.5 on 2019-11-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191103_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='continent',
            field=models.CharField(blank=True, choices=[('africa', 'africa'), ('asia', 'asia'), ('europe', 'europe'), ('americas', 'americas'), ('oceania', 'oceania')], default='europe', max_length=20, null=True),
        ),
    ]
