# Generated by Django 2.2.5 on 2019-11-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_destination_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
