# Generated by Django 2.2.5 on 2019-11-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_destination_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='views',
        ),
    ]
