# Generated by Django 2.2.5 on 2019-11-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_destcart_line_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destcart',
            name='line_total',
        ),
    ]
